package: parameter
generate:
  models: true
  embedded-spec: true
output:
  parameter.gen.go
output-options:
  skip-prune: true
import-mapping:
  https://doc.xk5.com/specs/externalref/schemas.yaml: github.com/cstcen/gore/doc/externalref/schema