// Package parameter provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen/v2 version v2.0.0 DO NOT EDIT.
package parameter

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	externalRef0 "github.com/cstcen/gore/doc/externalref/schema"
	"github.com/getkin/kin-openapi/openapi3"
)

// CharacterNoInPath defines model for CharacterNoInPath.
type CharacterNoInPath = externalRef0.CharacterNo

// GameIdInPath defines model for GameIdInPath.
type GameIdInPath = externalRef0.GameId

// MemberNoInPath defines model for MemberNoInPath.
type MemberNoInPath = externalRef0.MemberNo

// NicknamesInQuery 多个昵称使用逗号分隔
type NicknamesInQuery = externalRef0.Nicknames

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/5zRv28aMRQH8P/l246W+CFEkdcOiKGoqEtX93iA27PP2D6pCJ3UqerWBakVc6VGmbJE",
	"yRLln4Eg/ovId3BHQpREsD37y/uc35sjSpRJNGnvwOcwwgpFnmxevZ8IKyJPtp/09EfhJ+FQanCYUDBo",
	"oQgcUZUDg6VpKi0Nwb1NicFFE1Ii/PWtpRE43tQqtFbcutqBhSxj6ApFveGz7DiPnCwWQo59IPXlxVeq",
	"XehkcK/kZF9G30Jj19ODlOysRKd5Vap6n8NrmbIzsgDtjh/tM5T0XSgTB6RRrzdbrRYY/MyEA6k9jcmi",
	"XMTD/Kfu50EVdt5KPcbBHI+6579mp91ovKt3wDBKrBK+gNpPu9Uz+BxDcpGVxsskjGj9b7m6Pr/7e7n5",
	"f7G6ud0szrY//qx/X61//dwuF2AH9lfSWhKLpRPHHxzGI/UoAddpHDMkhrQwEhxg+fJdcZPdBwAA//85",
	"FjenJwMAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	pathPrefix := path.Dir(pathToFile)

	for rawPath, rawFunc := range externalRef0.PathToRawSpec(path.Join(pathPrefix, "https://doc.xk5.com/specs/externalref/schemas.yaml")) {
		if _, ok := res[rawPath]; ok {
			// it is not possible to compare functions in golang, so always overwrite the old value
		}
		res[rawPath] = rawFunc
	}
	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
