openapi: 3.0.1
info:
  contact:
    email: chestercen@tenvine.cn
    name: Chester
  description: Game Data Interface Service
  title: Gdis
  version: 2.0.0
servers:
  - url: https://api-{env}.xk5.com
    description: Development & Test Environment
    variables:
      env:
        enum:
          - sdev0
          - sdev
          - dev
          - dev2
          - dev3
          - mod
          - stg
        default: sdev0
        description: "sdev0: 藤蔓开发环境, sdev: 研发开发环境, dev/dev2: 研发测试环境"
  - url: https://api.xk5.com
    description: Production Environment
paths:
  /gdis/idip/{targetServiceType}/{targetServiceId}:
    post:
      security:
        - idip_auth: []
      parameters:
        - description: Service Type
          in: path
          name: targetServiceType
          required: true
          schema:
            enum:
              - game
              - service
            type: string
        - description: Service ID
          in: path
          name: targetServiceId
          required: true
          schema:
            enum:
              - SGXQ
            type: string
        - description: Data Signature
          in: query
          name: idip_sign
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/idip+json:
            schema:
              $ref: '#/components/schemas/IdipDataPacket'
        description: Request Content
        required: true
      responses:
        "200":
          content:
            application/idip+json:
              schema:
                $ref: '#/components/schemas/IdipDataPacket'
              examples:
                Success:
                  value: {
                    "body": {
                      "Result": 0,
                      "RetMsg": ""
                    },
                    "head": {
                      "Result": 0,
                      "RetErrMsg": "",
                      "Authenticate": "",
                      "Cmdid": 4087,
                      "PacketLen": 134,
                      "SendTime": 20230110,
                      "Seqid": 8102983023,
                      "ServiceName": "修改金币（游戏币）",
                      "Version": 20230109
                    }
                  }
                InvalidArguments:
                  value: {
                    "body": { },
                    "head": {
                      "Result": 400,
                      "RetErrMsg": "invalid signature: xxx",
                      "Authenticate": "",
                      "Cmdid": 4087,
                      "PacketLen": 134,
                      "SendTime": 20230110,
                      "Seqid": 8102983023,
                      "ServiceName": "修改金币（游戏币）",
                      "Version": 20230109
                    }
                  }
          description: OK
      summary: For Tencent IDIP platform use
      tags:
        - External
  /gdis/{sourceType}/{targetServiceType}/{targetServiceId}/{serviceName}:
    post:
      parameters:
        - description: Source type
          in: path
          name: sourceType
          required: true
          schema:
            enum:
              - console
              - platform
            type: string
        - description: Service Type
          in: path
          name: targetServiceType
          required: true
          schema:
            enum:
              - game
              - service
            type: string
        - description: Service ID
          in: path
          name: targetServiceId
          required: true
          schema:
            enum:
              - SGXQ
            type: string
        - description: kebab-case
          in: path
          name: serviceName
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              additionalProperties: true
        description: Request content
        required: false
      responses:
        "200":
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/DataResult'
                  - type: object
                    properties:
                      data:
                        type: object
                        additionalProperties: true
                        example: { "before": 10, "after": 20 }
              examples:
                Success:
                  value: { "code": 0, "message": "", data: { "before": 10, "after": 20 } }
                ServiceError:
                  $ref: "#/components/examples/ServiceError"
          description: OK
      security:
        - Internal: [ ]
      summary: Routing requests
      tags:
        - Internal
components:
  parameters:
    SourceType:
      description: Source type
      in: path
      name: sourceType
      required: true
      schema:
        enum:
          - console
          - platform
        type: string
    targetServiceType:
      description: Service Type
      in: path
      name: targetServiceType
      required: true
      schema:
        enum:
          - game
          - service
        type: string
    targetServiceId:
      description: Service ID
      in: path
      name: targetServiceId
      required: true
      schema:
        enum:
          - SGXQ
        type: string
    serviceName:
      description: kebab-case
      in: path
      name: serviceName
      required: true
      schema:
        type: string
    Authorization:
      description: eyJhbGciOiJIUzI1NiJ9.eyJhZ2VudCI6IlhLNV9T...
      in: header
      name: Authorization
      required: true
      schema:
        type: string
  schemas:
    IdipDataPacket:
      properties:
        body:
          type: object
          additionalProperties: true
          description: 包体信息
          example: { "Result": 0, "RetMsg": "" }
        head:
          $ref: '#/components/schemas/IdipHeader'
      type: object
      required:
        - head
        - body
      description: >
        required prefix: "data_packet=", e.g. "data_packet={'head': .....}
    IdipHeader:
      description: 包头信息
      properties:
        Authenticate:
          type: string
          description: 加密串
          example: ""
        Cmdid:
          type: integer
          format: uint32
          description: 命令ID
          example: 4087
        PacketLen:
          type: integer
          format: uint32
          description: 包长
          example: 134
          nullable: true
        Result:
          type: integer
          format: int32
          description: |
            错误码,返回码类型：0：处理成功，需要解开包体获得详细信息,1：处理成功，但包体返回为空，不需要处理包体（eg：查询用户角色，用户角色不存在等），其他错误,小于-100 ：用户自定义错误，需要填写szRetErrMsg
          example: 0
        RetErrMsg:
          type: string
          description: 错误信息
          example: ""
        SendTime:
          type: integer
          format: uint32
          description: 发送时间YYYYMMDD对应的整数
          example: 20230110
        Seqid:
          type: integer
          format: uint32
          description: 流水号
          example: "8102983023"
        ServiceName:
          type: string
          description: 服务名
          example: 修改金币（游戏币）
        Version:
          type: integer
          format: uint32
          description: 版本号
          example: 20230109
      type: object
      required:
        - PacketLen
        - Cmdid
        - Seqid
        - ServiceName
        - SendTime
        - Version
        - Authenticate
    DataResult:
      properties:
        code:
          type: integer
          example: 0
        message:
          example: OK
          type: string
      type: object
      required:
        - code
        - message
  securitySchemes:
    Internal:
      in: header
      name: Authorization
      type: apiKey
    idip_auth:
      type: apiKey
      in: query
      name: idip_sign
  examples:
    ServiceError:
      value: { "code": 500, "message": "Service error, please contact us" }
    InvalidArgument:
      value: { "code": 400, "message": "invalid request body" }
