// Package response provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen/v2 version v2.0.0 DO NOT EDIT.
package response

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	externalRef0 "github.com/cstcen/gore/doc/externalref/schema"
	"github.com/getkin/kin-openapi/openapi3"
)

// BadRequest defines model for BadRequest.
type BadRequest = externalRef0.BaseResultResponse

// InternalServerError defines model for InternalServerError.
type InternalServerError = externalRef0.BaseResultResponse

// NotFound defines model for NotFound.
type NotFound = externalRef0.BaseResultResponse

// Unauthorized defines model for Unauthorized.
type Unauthorized = externalRef0.BaseResultResponse

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/6yUQW/bPAyG/4rA7zsaiItlF9/WYQN66SHbTsMwsDITq3NIVaKzdUH++yDLTrrWSRcg",
	"NwHi+5AvRXELVtZemFgjVFugX7j2LfXna6wX9NBR1BveYOvqa6kf08UG247SwUpNUM3LsiznBawpRlwR",
	"VOByvAlZbu6ScLcr4IaVAmP7icKGwocQJEwA3yZg+RSoDe1hS3Qt1abuyKgYZOMGqKGel/Lcin6Ujuv3",
	"DQa0SmGy7HlZvnmaxY7R5idGw6JmmSA98Qtjp40E95vqoR3vrKUYP8sP4kn8VVleTXUFe9137YW7BA8U",
	"vXB83vYMYyXuj+h96yyqE57dR+F/fq//Ay2hgv9mh7eejcLZtCpVFW1DazwGyLdJH2lBsWt1MbjInmqK",
	"NjifqoUq1WZGV8fn4AyzRwgnrU5pLm10zGFyEjNkOYzkmT4nJ/mky5eKS3u8FTXZy7OPcaa31//USaOv",
	"yC/t+i+jB/jw9V4Qqi34IJ6Cuuw2r4Ut6KPP20BpRf1o7FfE/jJqcLyCvBseOhdSb79mxCH+WzHGy909",
	"Wc1VO14KVNy1bQHiidE7qAAK8KhNzDe7PwEAAP//ZXR8NvgFAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	pathPrefix := path.Dir(pathToFile)

	for rawPath, rawFunc := range externalRef0.PathToRawSpec(path.Join(pathPrefix, "https://doc.xk5.com/specs/externalref/schemas.yaml")) {
		if _, ok := res[rawPath]; ok {
			// it is not possible to compare functions in golang, so always overwrite the old value
		}
		res[rawPath] = rawFunc
	}
	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
